apiVersion: v1
kind: Service
metadata:
  name: {{ include "student-producer-app.fullname" . }}-svc
  labels:
    {{- include "student-producer-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "student-producer-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: "TCP"
      name: http
      port: {{ .Values.service.port }} # The port that the service is running on in the cluster
      targetPort: {{ .Values.service.port }} # The port exposed by the service
