apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "student-producer-app.fullname" . }}
  labels:
    {{- include "student-producer-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "student-producer-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "student-producer-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: aroralalit/student-producer:1.0.0
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.port }}