apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unification-service.fullname" . }}
  labels:
    {{- include "unification-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
    {{- include "unification-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "unification-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - mountPath: {{ .Values.configPath }}/application.properties
              name: osl-config
              subPath: application.properties
            - mountPath: {{ .Values.ssl.certs }}/server-keystore.jks
              name: osl-secret
              subPath: server-keystore.jks
            - mountPath: {{ .Values.ssl.certs }}/server-truststore.jks
              name: osl-secret
              subPath: server-truststore.jks
          env:
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-configmap  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-configmap
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: postgres_password
            - name: BROKER_URL # Setting AMQ_USER from Secret
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-configmap
                  key: brokerUrl
            - name: AMQ_USER # Setting AMQ_USER from Secret
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: artemis-user
            - name: AMQ_PASSWORD # Setting AMQ_PASSWORD from Secret
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: artemis-password
            - name: PATH # Setting path for configs like application properties and log4j.xml
              value: {{ .Values.configPath }}

      volumes:
        - name: osl-secret
          secret:
            secretName: {{ .Chart.Name }}-secret
        - name: osl-config
          configMap:
            name: {{ .Chart.Name }}-configmap