apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "unification-service.fullname" . }}-claim
  labels:
    {{- include "unification-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi